// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/13/2026, 11:23:28 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/izzatillo/Desktop/nuxt-dashboard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/izzatillo/Desktop/nuxt-dashboard/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/izzatillo/Desktop/nuxt-dashboard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/izzatillo/Desktop/nuxt-dashboard/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/izzatillo/Desktop/nuxt-dashboard/plugins/**/*.{js,ts,mjs}","/Users/izzatillo/Desktop/nuxt-dashboard/composables/**/*.{js,ts,mjs}","/Users/izzatillo/Desktop/nuxt-dashboard/utils/**/*.{js,ts,mjs}","/Users/izzatillo/Desktop/nuxt-dashboard/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/izzatillo/Desktop/nuxt-dashboard/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/izzatillo/Desktop/nuxt-dashboard/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/izzatillo/Desktop/nuxt-dashboard/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;